### ISSUE TITLE
[Feature] Configurable base size

### ISSUE THREAD

**Issue by JesusTheHun** [jan-dh/figma-tailwindcss#13]
**Is your feature request related to a problem? Please describe.**

I started to convert my figma to html with a base size of 10px instead of 16px (as it's the approach used by many) but now I would like to try your plugin and I can't because I would have to rewrite everything.

**Describe the solution you'd like**
Make the base size configurable.

**Describe alternatives you've considered**
Rewrite everything is not acceptable solution.

**Comment by JesusTheHun** [comment]
I have the following : 

```css
html {
  font-size: 62.5%;
}
```

Now in my design everything is in `px`. From what I understand your plugin will convert that in `rem` using a base font size of 16px, which will break my current (still in progress) implementation.
I would like the possibility to change the base font size the plugin uses to convert `px` to `rem`.

**Comment by jan-dh** [comment]
If you use tailwind for all of your font-sizes, (e.g. `@apply font-sm`) in your classes, why would you ever need to  touch the default font size of your html? You're not writing any font-sizes in your css so you shouldn't change the base font-size? That's the whole point of tailwindcss. There are a couple of arguments to use 16px as a base font size: 

- if you keep dividing 16 by 2, then you always get another even number, but if you divide 10 by 2, then you get and odd number.
- The tailwind spacing system is based around rem sizes. That way you can It's easier

That being said, I think the practice of changing the font-size to 62.5% have easier calculations is a bit hacky and I can't see any real arguments in supporting it.
