### ISSUE TITLE
Value has no property

### ISSUE THREAD

**Issue by MichalGallovic** [jan-dh/figma-tailwindcss#2]
### Description
Hey @jan-dh I like the idea of your plugin! But currently it seems to be broken. This is the output I get into console

```
TypeError: value has no property
    at <anonymous> (PLUGIN_13_SOURCE)
    at forEach (native)
    at <anonymous> (PLUGIN_13_SOURCE)
    at <anonymous> (PLUGIN_13_SOURCE)
    at call (native)
    at n (PLUGIN_13_SOURCE)
    at <anonymous> (PLUGIN_13_SOURCE)
    at <anonymous> (PLUGIN_13_SOURCE:1)
    at call (native)
    at <eval> (PLUGIN_13_SOURCE:3)
```

### Steps to reproduce

1. Right click element
2. Run plugin
3. Nothing happens

Is this how I'm supposed to run this ? Thanks.

**Comment by jan-dh** [comment]
You wouldn't have to select any element, the plugin reads the data from the document. Could you maybe share your design with me so I can debug the error? Just tried running the plugin here and have no issues with it.

**Comment by austriker27** [comment]
@jan-dh I'm also getting this error on a design file. It works on some files but not a specific one I'm trying to use. Unfortunately I can't share it because it has client specific information in it.

**Comment by austriker27** [comment]
@jan-dh  Good news, I found a public figma file that gives me the same sort of error: https://www.figma.com/community/file/820337605519256142

Hopefully that helps! This plugin seems awesome!

**Comment by jan-dh** [comment]
I just released a new update, should be working fine now. The issue was that I wasn't taking into account the gradients. Thanks for the issue. I'm always looking for feature requests and feedback on the plugin, so don't hold back in giving any feedback.

**Comment by MichalGallovic** [comment]
Thank you!

**Comment by austriker27** [comment]
Awesome, thanks @jan-dh !

**Comment by jan-dh** [comment]
Added gradient detection that notifies you if there are gradient colors so you could manually add them to the theme if you want.
