### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by RapidoBots** [jan-dh/figma-tailwindcss#39]
How to use this? 
There is no `How to use this` information? 
Idea is cool but I don't know what I'm looking at. 
I don't know what steps to follow.

**Comment by jan-dh** [comment]
So, steps how to use this:

1. Create a design in Figma, while you create a design make sure use:
- text styles to get your font size, font families:
<img width="182" alt="image" src="https://user-images.githubusercontent.com/5801781/196520800-2bfded69-f773-45cc-9678-9c80cbc835de.png">
- color styles to get an overview of your colors (group them under a key if you want)
<img width="197" alt="image" src="https://user-images.githubusercontent.com/5801781/196520765-acf06577-648a-4f9c-bf9b-f55905209890.png">
- effect styles:
<img width="229" alt="image" src="https://user-images.githubusercontent.com/5801781/196520875-21f54244-b43e-4628-b142-96c93b133f6d.png">

Once you want to export this to a tailwind config file, run the plugin, you'll see something like this:
for colors:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/5801781/196520987-7787d1c3-1505-4f18-8eb8-7ef9cf2dea11.png">
for fonts: 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/5801781/196521055-2aaf91c7-ee8b-4da1-affa-d4174c6a3c39.png">
effect styles:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/5801781/196521100-c2e693d7-dcf7-4160-b2f6-adc790868871.png">
the config file:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/5801781/196521152-ebd4c9c7-3322-4461-8f36-62f7b3283baf.png">

and now you download that config file and use that in your tailwind project.
