### ISSUE TITLE
[BUG] no longer works with new Figma update?

### ISSUE THREAD

**Issue by MattAppleton** [jan-dh/figma-tailwindcss#9]
### Description

The plugin no longer works, if I select a swatch and run the plugin it says

"running tailwinds"

and then nothing...

- Figma version: 90
Build 4
Copyright © 2020 Figma, Inc.

- OS version:

Mac OSX Catalina 10.15.7

**Comment by jan-dh** [comment]
Just tested it on the same version of Figma without any problem. Could you maybe share the file you encounter this issue with?

**Comment by MattAppleton** [comment]
> Just tested it on the same version of Figma without any problem. Could you maybe share the file you encounter this issue with?

@jan-dh I think you are right, runs fine on a simpler Figma file (sorry, I should have checked!)

If you are curious, here's the offending file — interested to know what might be causing the issue!
[Youngster (finals).fig.zip](https://github.com/jan-dh/figma-tailwindcss/files/5585928/Youngster.finals.fig.zip)

Great work on the plugin by the way. Most useful.

**Comment by jan-dh** [comment]
@MattAppleton Found the issue. Turns out the color `YNG/green/100` didn't have any paint styles applied to it. Made an update, wil release soon together with some minor updates. In the meantime, if you update the color `YNG/green/100` to have a transparent background, the plugin should run fine.

**Comment by jan-dh** [comment]
@MattAppleton published a new release with a fix
